image: Ubuntu

stack: python 3.8

cache:
  # Linux
  - "/home/appveyor/.cache/pip"

build: off

install:
- python --version
- pip install poetry
- poetry export --without-hashes --format requirements.txt --output requirements.txt
- pip install -r requirements.txt

test_script:
- poetry run python main.py